[project]
name = "radio_backend"
version = "1.0"
dependencies = [
  "django==5.2.*",
  "gunicorn",
  "psycopg2",
]

[tool.black]
line-length = 79

[tool.pycln]
all = true
default_section = "THIRDPARTY"
known_first_party = "django"
